# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Conner Wilczewski
title: Computer Engineer
email: Wilczew9@msu.edu
# email_title: Email (Email title override)
phone: 248-639-9659
# phone_title: Phone (Phone title override)


# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  Conwilcz
facebook_username: conner.wilczewski

# Additional icon links
# additional_links:
# - title: Link name
  # icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
  # url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: /images/me.jpg 
about_content: | # this will include new lines to allow paragraphs
  Greetings, and welcome to my page. I love technology. As someone who's grown up with ever changing technology year after year, i've discovered a passion for watching the growth of technology over the years. 
  My goal is to one day contribute to the advancement of technology, to help mankind with problems that can be solved with technologial solutions. If you happen to share the same fondness of technology as I do, then we may have a lot in common.
  
# so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.

# You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
#  - Lists
#  - Tables
#  - <a href="google.com">Links</a>
#  - Images ![alt text](/images/landscape-trees.jpg "Trees")

content:
border: weak
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Caddying
        additional_links:
          - title:  For more on caddying...
            icon: fab fa-github
            url: https://www.usga.org/content/dam/usga/pdf/host-sites/Caddies.pdf
        sub_title: Honor's Caddy
        caption: (June 2016 - present) 
        description: | # this will include new lines to allow paragraphs
          - Skilled in assisting golf players by carrying bags, providing accurate yardage, advising on club selection, and reading greens. 
          - Proficient in maintaining a high standard of etiquette and supporting players in strategic game decisions. 
          - Demonstrated ability to build rapport with club members, enhancing their golfing experience and upholding the club’s reputation for exceptional guest service.
          
          
          ![alt text](/images/golfing.jpg "golfcourse")
  - title: Education
    layout: list
    content:
      - layout: left
        title: Michigan State University
        sub_title: Senior in Computer Engineering
        caption: (eg. 2021 - present)
        description: | # this will include new lines to allow paragraphs
          Computer engineering involves different aspects of technology, one of the most noticeable being circuitry and the understanding of electrical engineering principles and their applications. 
          Another important facet is the computer side of engineering, the programming and interworking's behind technology. 
          Every course has been instrumental in the broadening of my understanding of computer engineering, and led to the further interest of where technology will go next.


                      
          ![alt text](/images/msueduc.jpg "campus")
  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      **Speaking:** Back in highschool, I was apart of a competitive speaking club, which was apart of the **Michigan Interscholastic Forensics Association** (MIFA). 
      In my junior and senior year, I went on to states and obtained **5th** place overall in my catagory, oratory.

      **Handiwork:** In my free time, I help out with fundraisers for local charities. These fundraisers include all sorts of actvities per charity. My favorite local charity is the **Walled Lake Civic Fund**, as all proceeds go to a huge firework show for all residents and friends of Walled Lake!

      **Certification in Computer Networking and Hardware:** During my junior and senior years of highschool, I took part of a dual enrollment program to take college level classes at **Oakland Schools Technical Campus**. These classes made me proficent in Networking and Hardware troubleshooting and usage.
  - title: Extra Information # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: middle  
        description: | # this will include new lines to allow paragraphs
          If you are curious about other aspects of my life, feel free to explore via the links below!

          

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
